'use strict';
const assert = require('node:assert/strict');
const { EventEmitter } = require('node:events');
const { createUpdates } = require('../src/updates');
(async () => {
  const updater = new EventEmitter();
  let checks = 0, downloads = 0, installs = 0;
  updater.checkForUpdates = async () => { checks++; updater.emit('update-available', { version: '0.1.2' }); };
  updater.downloadUpdate = async () => { downloads++; updater.emit('download-progress', { percent: 51.2 }); updater.emit('update-downloaded', { version: '0.1.2' }); };
  updater.quitAndInstall = (silent, reopen) => {
    assert.equal(silent, true);
    assert.equal(reopen, true);
    installs++;
  };
  const updates = createUpdates(updater, { enabled: true, version: '0.1.1' });
  assert.equal(updater.autoDownload, false);
  assert.equal(updater.autoInstallOnAppQuit, false);
  await updates.check();
  assert.equal(updates.state().status, 'ready');
  assert.equal(downloads, 1);
  await updates.check();
  assert.equal(checks, 1);
  assert.equal(updates.state().status, 'ready');
  assert.equal(installs, 0);
  await updates.check();
  assert.equal(installs, 0);
  await updates.act();
  await updates.act();
  assert.equal(installs, 1);
  updater.emit('error', new Error('Installer could not start'));
  assert.equal(updates.state().status, 'error');
  await updates.act();
  assert.equal(updates.state().status, 'ready');
  const failing = new EventEmitter();
  failing.checkForUpdates = async () => { throw new Error('offline'); };
  const retry = createUpdates(failing, { enabled: true, version: '0.1.1' });
  await retry.check();
  assert.equal(retry.state().status, 'error');
  failing.checkForUpdates = async () => failing.emit('update-not-available');
  await retry.act();
  assert.equal(retry.state().status, 'current');
  const disabled = createUpdates(new EventEmitter(), { enabled: false, version: 'dev' });
  await disabled.act();
  assert.equal(disabled.state().status, 'disabled');
  const slow = new EventEmitter();
  let finishDownload, downloadCalls = 0, checkCalls = 0;
  slow.checkForUpdates = async () => { checkCalls++; slow.emit('update-available', { version: '0.1.3' }); };
  slow.downloadUpdate = () => {
    downloadCalls++;
    return new Promise(resolve => { finishDownload = () => {
      slow.emit('update-downloaded', { version: '0.1.3' }); resolve();
    }; });
  };
  const background = createUpdates(slow, { enabled: true, version: '0.1.2' });
  const checking = background.check();
  await new Promise(resolve => setImmediate(resolve));
  assert.equal(background.state().status, 'downloading');
  await background.act();
  await background.check();
  assert.equal(checkCalls, 1);
  assert.equal(downloadCalls, 1);
  finishDownload();
  await checking;
  assert.equal(background.state().status, 'ready');
  slow.emit('error', new Error('Download failed'));
  slow.downloadUpdate = async () => { throw new Error('Offline'); };
  await background.act();
  assert.equal(background.state().status, 'error');
  slow.downloadUpdate = async () => slow.emit('update-downloaded', { version: '0.1.3' });
  await background.act();
  assert.equal(background.state().status, 'ready');
  console.log('Update flow checks passed.');
})().catch(error => { console.error(error); process.exitCode = 1; });
